# This is Intellij IDEA HTTP collection
# It's plain text and one can run it directly from Ultimate Intellij IDEA
# or VS Code with httpyac plugin

### Checking health endpoint
GET http://localhost:8080/health

### Get all funds
GET http://localhost:8080/funds

### Create new fund
POST http://localhost:8080/funds
Content-Type: application/json
Accept: application/json

{
  "name": "Test Fund 1",
  "description": "testdescription"
}

### Get fund by ID
GET http://localhost:8080/funds/a0e2e16c-0223-4970-a9c3-a8b3de6ca4e9

### Update fund's description
PUT http://localhost:8080/funds/a0e2e16c-0223-4970-a9c3-a8b3de6ca4e9
Content-Type: application/json
Accept: application/json

{
  "description": "New Life!!!"
}

### Get list of all investors
GET http://localhost:8080/investors

### Create new investor
POST http://localhost:8080/investors
Content-Type: application/json
Accept: application/json

{
  "name": "Test Investor 1",
  "email": "good@example.com"
}

### Create new investor with bad email fails
POST http://localhost:8080/investors
Content-Type: application/json
Accept: application/json

{
  "name": "Test Investor 2",
  "email": "bad#example.com"
}

### Get investor by ID
GET http://localhost:8080/investors/134b8f44-fce3-4480-8617-d09f8bf3d1e8
