# This is Intellij IDEA HTTP collection
# It's plain text and one can run it directly from Ultimate Intellij IDEA
# or VS Code with httpyac plugin

### Checking health endpoint
GET http://localhost:8080/health

### Get all funds
GET http://localhost:8080/funds

### Create new fund
POST http://localhost:8080/funds
Content-Type: application/json
Accept: application/json

{
  "name": "Test Fund 2",
  "description": "testdescription"
}

### Get fund by ID
GET http://localhost:8080/funds/11111111-1111-1111-1111-111111111111

### Update fund's description
PUT http://localhost:8080/funds/11111111-1111-1111-1111-111111111111
Content-Type: application/json
Accept: application/json

{
  "description": "New Life!!!"
}

### Delete fund
DELETE http://localhost:8080/funds/11111111-1111-1111-1111-111111111111

### Get list of all investors
GET http://localhost:8080/investors

### Create new investor
POST http://localhost:8080/investors
Content-Type: application/json
Accept: application/json

{
  "name": "Test Investor 2",
  "email": "good2@example.com"
}

### Create new investor with bad email fails
POST http://localhost:8080/investors
Content-Type: application/json
Accept: application/json

{
  "name": "Test Investor 2",
  "email": "bad#example.com"
}

### Get investor by ID
GET http://localhost:8080/investors/33333333-3333-3333-3333-333333333333

### Delete investor by ID
DELETE http://localhost:8080/investors/33333333-3333-3333-3333-333333333333

### Get a list of all transactionsd
GET http://localhost:8080/transactions

### Create new permission
POST http://localhost:8080/fund-permissions
Content-Type: application/json
Accept: application/json

{
  "fund_id": "22222222-2222-2222-2222-222222222222",
  "investor_id": "33333333-3333-3333-3333-333333333333"
}

### Delete permission
DELETE http://localhost:8080/fund-permissions/22222222-2222-2222-2222-222222222222/33333333-3333-3333-3333-333333333333

### Create new transaction
POST http://localhost:8080/transactions
Content-Type: application/json
Accept: application/json

{
  "fund_id": "22222222-2222-2222-2222-222222222222",
  "investor_id": "33333333-3333-3333-3333-333333333333",
  "transaction_type": "CONTRIBUTION",
  "transaction_effect": "DEBIT",
  "amount": 50.50,
  "description": "Initial contribution"
}

### Report for fund
GET http://localhost:8080/reports/fund/22222222-2222-2222-2222-222222222222

### Report for fund with date range
GET http://localhost:8080/reports/fund/22222222-2222-2222-2222-222222222222?from_date=2026-07-30T00:00:00Z&to_date=2026-07-31T23:59:59Z
