CREATE TABLE fund (
  id TEXT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  description TEXT,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE investor (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fund_transaction (
  id TEXT PRIMARY KEY,

  fund_id TEXT NOT NULL REFERENCES fund(id),
  investor_id TEXT NOT NULL REFERENCES investor(id),

  transaction_type TEXT NOT NULL,
  transaction_effect TEXT NOT NULL,
  amount NUMERIC NOT NULL CHECK (amount > 0),
  transaction_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,

  description TEXT,

  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
